[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
hello_world = "B7ihZyoXZ1fwAY3TugkiFJ6SXkzJwMuQrxrekBaSmn32"
multisig = "44444444444444444444444444444444444444444444"

[workspace]
members = ["programs/hello-world", "programs/multisig"]
